# Generated by Django 2.1.2 on 2018-11-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PigPredict_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_clothe',
            name='CLOTHE',
            field=models.CharField(choices=[('FVF2184', 'FVF2184'), ('FVF2429', 'FVF2429'), ('FVF2666', 'FVF2666')], default='FVF2666', max_length=256),
        ),
    ]
