# Generated by Django 2.1.2 on 2018-11-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PigPredict_app', '0002_auto_20181130_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab_clothe',
            name='CLOTHE',
            field=models.CharField(choices=[('FVF2666', 'FVF2666'), ('FVF2184', 'FVF2184'), ('FVF2429', 'FVF2429')], default='FVF2666', max_length=256),
        ),
    ]
